export const EMPLOYEE_LIST = "EMPLOYEE_LIST"
export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCESS"
export const EMPLOYEE_LIST_FAILURE = "EMPLOYEE_LIST_FAILURE"

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE"


export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS"
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE"


export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS"
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE"